# Generated by Django 4.0.1 on 2022-10-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storeobjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('object_type', models.CharField(choices=[('CHEMICAL', 'Chemical'), ('GLASSWARE', 'Glassware'), ('INSTRUMENT', 'Instrument')], max_length=10)),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('CHEMICAL', 'Chemical'), ('GLASSWARE', 'Glassware'), ('INSTRUMENT', 'Instrument')], default='CHEMICAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consumer_type', models.CharField(choices=[('PHYSICAL', 'Physical Lab'), ('ORGANIC', 'Organic Lab'), ('INORGANIC', 'Inorganic Lab'), ('PERSONAL', 'Personal')], max_length=20)),
                ('room_number', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administration.building')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('room_number', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administration.building')),
                ('chemicals', models.ManyToManyField(to='storeobjects.ChemicalObj')),
                ('glasswares', models.ManyToManyField(to='storeobjects.GlasswareObj')),
                ('instruments', models.ManyToManyField(to='storeobjects.InstrumentObj')),
            ],
        ),
        migrations.CreateModel(
            name='IssueObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('object_type', models.CharField(choices=[('CHEMICAL', 'Chemical'), ('GLASSWARE', 'Glassware'), ('INSTRUMENT', 'Instrument')], max_length=10)),
                ('old_total', models.FloatField()),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='store_consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.storeconsumer'),
        ),
        migrations.CreateModel(
            name='InstrumentTempShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_obj', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeobjects.instrumentobj')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_total', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeobjects.instrumentobj')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='GlasswareTempShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_obj', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('glassware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeobjects.glasswareobj')),
            ],
        ),
        migrations.CreateModel(
            name='GlasswareShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_total', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('glassware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeobjects.glasswareobj')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalTempShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_obj', models.BooleanField(default=False)),
                ('quantity', models.FloatField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeobjects.chemicalobj')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_total', models.FloatField()),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeobjects.chemicalobj')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.shipment')),
            ],
        ),
    ]
