# Generated by Django 3.2.8 on 2022-01-26 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_store_material_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField()),
                ('note', models.CharField(blank=True, default='Write something about the shipment in 200 characters', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.instrument')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='GlasswareShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('glassware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.glassware')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.chemical')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.shipment')),
            ],
        ),
    ]
