# Generated by Django 3.2.8 on 2022-01-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_shipment_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('building_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('note', models.CharField(blank=True, default='Write something about the issue in 200 characters', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.storeconsumer')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.instrument')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.storeissue')),
            ],
        ),
        migrations.CreateModel(
            name='GlasswareIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('glassware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.glassware')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.storeissue')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.chemical')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.storeissue')),
            ],
        ),
    ]
