# Generated by Django 4.0.1 on 2022-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_tables_for_issue_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalshipment',
            old_name='quantity',
            new_name='new_quantity',
        ),
        migrations.RenameField(
            model_name='glasswareshipment',
            old_name='quantity',
            new_name='new_quantity',
        ),
        migrations.RenameField(
            model_name='instrumentshipment',
            old_name='quantity',
            new_name='new_quantity',
        ),
        migrations.AddField(
            model_name='chemicalshipment',
            name='old_quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glasswareshipment',
            name='old_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentshipment',
            name='old_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
