# Generated by Django 4.0.1 on 2022-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_rename_quantity_chemicalshipment_new_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconsumer',
            name='consumer_type',
            field=models.CharField(choices=[('Lab', 'LAB'), ('Researcher', 'RESEARCHER')], default='RESEARCHER', max_length=20),
            preserve_default=False,
        ),
    ]
