# Generated by Django 4.0.1 on 2022-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_storeconsumer_consumer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalissue',
            old_name='quantity',
            new_name='new_quantity',
        ),
        migrations.RenameField(
            model_name='glasswareissue',
            old_name='quantity',
            new_name='new_quantity',
        ),
        migrations.RenameField(
            model_name='instrumentissue',
            old_name='quantity',
            new_name='new_quantity',
        ),
        migrations.AddField(
            model_name='chemicalissue',
            name='old_quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glasswareissue',
            name='old_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentissue',
            name='old_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
