# Generated by Django 4.0.1 on 2022-02-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_rename_quantity_chemicalissue_new_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeissue',
            name='carrier_name',
            field=models.CharField(blank=True, default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='storeconsumer',
            name='consumer_type',
            field=models.CharField(choices=[('Physical_LAB', 'Physical Lab'), ('Organic_LAB', 'Organic Lab'), ('Inorganic_LAB', 'Inorganic Lab'), ('PERSONAL', 'Personal')], max_length=20),
        ),
    ]
