# Generated by Django 4.0.1 on 2022-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_storeissue_carrier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconsumer',
            name='consumer_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Lab'), ('ORGANIC', 'Organic Lab'), ('INORGANIC', 'Inorganic Lab'), ('PERSONAL', 'Personal')], max_length=20),
        ),
    ]
