# Generated by Django 4.0.1 on 2022-03-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_storeconsumer_consumer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='amount',
            new_name='quantity',
        ),
    ]
