# Generated by Django 4.0.1 on 2022-03-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_rename_amount_chemical_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalshipment',
            old_name='new_quantity',
            new_name='old_total',
        ),
        migrations.RenameField(
            model_name='chemicalshipment',
            old_name='old_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='glasswareshipment',
            old_name='new_quantity',
            new_name='old_total',
        ),
        migrations.RenameField(
            model_name='glasswareshipment',
            old_name='old_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='instrumentshipment',
            old_name='new_quantity',
            new_name='old_total',
        ),
        migrations.RenameField(
            model_name='instrumentshipment',
            old_name='old_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='note',
        ),
    ]
