# Generated by Django 4.0.1 on 2022-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_instrumenttempshipment_glasswaretempshipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('CHEMICAL', 'Chemical'), ('GLASSWARE', 'Glassware'), ('INSTRUMENT', 'Instrument')], default='CHEMICAL', max_length=10),
        ),
    ]
