# Generated by Django 4.0.1 on 2022-04-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_issuecart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeissue',
            name='issue_date',
        ),
    ]
