# Generated by Django 4.0.1 on 2022-10-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAS_RN', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('molecular_formula', models.CharField(max_length=300)),
                ('molecular_weight', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.instrument')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.manufacturer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.supplier')),
            ],
            options={
                'unique_together': {('instrument', 'manufacturer', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='GlasswareObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(blank=True, default=0)),
                ('material_type', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('glassware', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.glassware')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.manufacturer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.supplier')),
            ],
            options={
                'unique_together': {('glassware', 'manufacturer', 'supplier', 'size', 'material_type')},
            },
        ),
        migrations.CreateModel(
            name='ChemicalObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('SOLID', 'Solid'), ('LIQUID', 'Liquid'), ('GAS', 'Gas'), ('PLASMA', 'Plasma')], max_length=20)),
                ('quantity', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.chemical')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.manufacturer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeobjects.supplier')),
            ],
            options={
                'unique_together': {('chemical', 'purity', 'manufacturer', 'supplier', 'state')},
            },
        ),
    ]
